function Chapter2() {
    return (
        <>
            <h2 className="story-title">Chapter 2: </h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nisl justo, malesuada sed turpis sagittis, iaculis tristique erat. Nullam semper orci eget elementum tempus. Nunc pellentesque nulla id est sollicitudin, id fringilla nisl varius. Donec ut dignissim leo, at dictum metus. In sollicitudin, arcu vel ullamcorper faucibus, lectus urna congue eros, porta porttitor dolor lacus ut mi. Integer egestas nunc orci, at tristique enim facilisis sit amet. Praesent ultricies massa id libero malesuada, in tristique augue vestibulum. Suspendisse iaculis finibus libero vel condimentum. In eu enim vestibulum justo molestie mattis at at quam. Etiam orci erat, pellentesque nec tristique nec, lobortis in mauris.</p>
            <p>Nam in scelerisque magna, blandit sagittis nisi. Donec suscipit elit eget nisi iaculis, placerat scelerisque metus vestibulum. Proin a augue in nisi scelerisque dapibus nec eget risus. Nulla ullamcorper odio augue, a convallis velit molestie ac. Sed quis ipsum a odio varius dictum in sit amet ex. Sed ac ante quis orci gravida posuere vel sollicitudin libero. Sed aliquam magna ut malesuada cursus. Quisque placerat ullamcorper pharetra. Praesent et neque mattis nulla tempor dignissim. Praesent arcu leo, vestibulum lobortis aliquam at, aliquam id nisi. Fusce fringilla tincidunt dolor in imperdiet. Aenean sit amet lectus placerat, pretium sapien in, commodo metus.</p>
            <p>Fusce quis egestas libero. In et nisi nec risus condimentum pharetra nec at ligula. Nunc nec est venenatis, porta sapien nec, consequat quam. Duis in lacus fringilla, ultricies urna non, fringilla elit. Vivamus non condimentum est. Fusce laoreet, leo non dapibus sodales, turpis dolor eleifend nunc, ut euismod est turpis a leo. Proin consectetur nisl ac ligula vulputate, ac pretium erat porttitor. Nulla maximus dapibus erat, sit amet volutpat augue.</p>
            <p>Sed libero lectus, pharetra quis nunc eu, faucibus ullamcorper nulla. Etiam commodo eget metus at sodales. Pellentesque in lorem bibendum lacus viverra molestie. Vivamus ornare eros at libero interdum, eget lobortis felis tempor. Maecenas tristique erat gravida hendrerit facilisis. Sed ac sem velit. Nullam convallis laoreet mi, nec vestibulum nulla egestas eget. Etiam justo lorem, facilisis sit amet consequat at, feugiat eget enim. Phasellus condimentum condimentum odio, id pulvinar dui auctor in. Aliquam sollicitudin purus ac viverra faucibus. Mauris consequat neque pulvinar nunc pulvinar viverra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ipsum mauris, pellentesque ac luctus eget, vehicula at lorem. Aenean volutpat congue justo in gravida. Vivamus eleifend consequat nisi vel hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
            <p>Suspendisse viverra quam a tempor vehicula. Vestibulum sed est sed justo pulvinar aliquam. Sed scelerisque suscipit tellus, eu dignissim nulla ultricies cursus. Nam tristique rhoncus tempus. Sed cursus, mi eget maximus cursus, tellus felis dictum urna, sit amet sagittis sem ex et eros. Pellentesque eros purus, placerat vel molestie et, fermentum sed enim. Ut ac scelerisque dolor. Proin justo felis, varius eget tempor et, condimentum volutpat urna. Morbi tristique elit eget nisi ullamcorper, ac auctor metus fringilla. Fusce congue mollis urna sed viverra. Donec pellentesque venenatis nibh, quis ultricies diam gravida et.</p>
        </>
    );
}

export default Chapter2;