function Chapter3() {
    return (
        <>
            <h2 className="story-title">Chapter 3: </h2>
            <p>Nam suscipit sem nulla, eu semper neque sagittis sodales. Phasellus efficitur suscipit lorem nec eleifend. Praesent quis pharetra sem. Praesent ut euismod dui. Suspendisse potenti. Cras tristique est nisi, eu efficitur erat varius a. Phasellus id tortor nec nibh pulvinar feugiat varius sit amet metus. Curabitur sed eros porta, aliquam libero non, pretium urna. Mauris fermentum suscipit tellus eu suscipit.</p>
            <p>Ut sed nisl scelerisque, condimentum nisi vel, accumsan dui. Mauris at nisi congue, commodo libero nec, lacinia massa. Sed viverra dictum gravida. Sed sollicitudin, eros sit amet posuere imperdiet, nisi leo pellentesque dui, ac fermentum ex dolor non nibh. Sed pretium ligula feugiat gravida ultrices. Pellentesque sed nisi cursus, aliquam erat luctus, aliquet ipsum. Sed sit amet lobortis lectus. Morbi non viverra ligula.</p>
            <p>Ut gravida suscipit dignissim. Nunc nec tincidunt odio. Aliquam erat volutpat. Phasellus vestibulum lorem id diam volutpat facilisis. Nunc pretium pellentesque nisl eu commodo. Duis eleifend, odio vitae interdum semper, enim tortor dapibus leo, ut placerat lectus nibh nec ex. Pellentesque lobortis augue eget nisi suscipit, vitae mollis mi eleifend. Sed tincidunt sit amet dui ut consectetur. Proin pellentesque pulvinar pharetra. Duis blandit posuere mi, ut semper risus laoreet nec. Etiam eros odio, finibus sed gravida eu, efficitur eu lectus. Fusce quis augue orci. Donec semper lorem tristique purus dapibus tincidunt.</p>
            <p>Praesent sollicitudin orci metus, sit amet efficitur sapien posuere vel. Phasellus scelerisque tellus sit amet tincidunt auctor. Nulla viverra blandit quam, ut maximus nibh iaculis vel. Sed volutpat lorem ut diam aliquam auctor. Quisque vestibulum dui augue, vitae pulvinar odio ornare nec. Nam accumsan volutpat enim, at rutrum tortor. Proin tempor convallis ipsum.</p>
            <p>Aenean tincidunt venenatis ex quis eleifend. Duis nec lacus vel risus elementum accumsan a id lacus. Quisque et felis in erat molestie commodo. Pellentesque rutrum mollis velit ut sodales. Proin vitae nisi dictum, suscipit felis at, faucibus arcu. Quisque elementum mattis erat ut dignissim. Sed erat ipsum, facilisis non ullamcorper ac, imperdiet in erat. Fusce laoreet sem posuere auctor pharetra. Curabitur non purus egestas, mollis ligula vitae, pretium leo. Fusce et efficitur diam.</p>
            <p>Aliquam ac ullamcorper nibh. Nullam dignissim laoreet enim nec faucibus. In hac habitasse platea dictumst. Vivamus sed bibendum erat. Aenean venenatis nisl rutrum, tincidunt tellus sed, vulputate nulla. Duis vitae pulvinar leo, faucibus mattis felis. Mauris porta magna elit, vitae consectetur felis condimentum a. Etiam eros nunc, iaculis nec leo eget, mattis ullamcorper ex.</p>
            <p>Etiam lacinia purus sit amet sem auctor tincidunt. Morbi non aliquam purus. In hac habitasse platea dictumst. Donec odio eros, molestie id egestas sit amet, tempor sit amet leo. Aenean malesuada nec metus id bibendum. Aenean hendrerit ornare iaculis. Mauris feugiat dapibus convallis. Cras congue mauris in accumsan scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin condimentum dignissim orci, ut pulvinar leo euismod sed. Donec purus enim, ullamcorper a nisi sed, elementum luctus eros.</p>
            <p>Vestibulum nec tempor diam. Morbi sit amet dignissim velit. Donec vel iaculis massa. Ut tincidunt scelerisque elit id blandit. Nullam mauris justo, commodo vitae pharetra vitae, condimentum non tortor. Proin pretium massa sit amet magna imperdiet venenatis. Vivamus ultrices ligula vel tortor imperdiet, efficitur dignissim risus volutpat. Nullam vel tempor tellus. In pretium eu nunc facilisis congue. Sed ornare lectus nisi, vehicula vehicula arcu ullamcorper ac. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <p>Phasellus urna felis, mollis ac bibendum eget, suscipit blandit leo. Suspendisse potenti. Vestibulum nisl ante, vestibulum ut cursus vel, rhoncus non quam. Fusce orci ex, porta vitae arcu a, condimentum auctor sapien. Ut porta orci ac ex facilisis tempor. Etiam luctus arcu id erat scelerisque vehicula. Nulla sagittis, orci non dignissim suscipit, ante odio ornare nisl, sit amet ullamcorper est elit ac quam. Sed tempor enim sed erat finibus, et sodales metus efficitur. Nulla nulla arcu, venenatis non orci nec, efficitur tempor dui. Donec imperdiet magna dolor, fermentum mollis lorem volutpat ac. Donec sodales purus iaculis vulputate auctor. Nulla facilisi. Quisque sem massa, dignissim ut massa a, dignissim sodales sapien. Donec convallis, quam sed convallis iaculis, augue mi consectetur ante, vel consequat est neque et purus.</p>
        </>
    );
}

export default Chapter3;